jobs:
- name: docker-devpi-publish
  public: true
  serial: true
  plan:
  - get: docker-devpi
    trigger: true
#  - put: docker-devpi-image-at-dockerhub
#    params: {build: docker-devpi}
  - put: docker-devpi-image-at-quay
    params: {build: docker-devpi}

resources:
- name: docker-devpi
  type: git
  source:
    uri: https://github.com/topiaruss/docker-devpi.git

#- name: docker-devpi-image-at-dockerhub
#  type: docker-image
#  source:
#    username: {{docker-username}}
#    password: {{docker-password}}
#    repository: topiaruss/docker-devpi
#
- name: docker-devpi-image-at-quay
  type: docker-image
  source:
    email: {{quay_io-email}}
    username: {{quay_io-username}}
    password: {{quay_io-password}}
    repository: quay.io/russf/docker-devpi
